/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BookingsService } from "../bookings.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BookingsCreateInput } from "./BookingsCreateInput";
import { Bookings } from "./Bookings";
import { BookingsFindManyArgs } from "./BookingsFindManyArgs";
import { BookingsWhereUniqueInput } from "./BookingsWhereUniqueInput";
import { BookingsUpdateInput } from "./BookingsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BookingsControllerBase {
  constructor(
    protected readonly service: BookingsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Bookings })
  @nestAccessControl.UseRoles({
    resource: "Bookings",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBookings(
    @common.Body() data: BookingsCreateInput
  ): Promise<Bookings> {
    return await this.service.createBookings({
      data: {
        ...data,

        service: data.service
          ? {
              connect: data.service,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        date: true,
        id: true,

        service: {
          select: {
            id: true,
          },
        },

        specialistId: true,
        status: true,
        time: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Bookings] })
  @ApiNestedQuery(BookingsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Bookings",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async bookingsItems(@common.Req() request: Request): Promise<Bookings[]> {
    const args = plainToClass(BookingsFindManyArgs, request.query);
    return this.service.bookingsItems({
      ...args,
      select: {
        createdAt: true,
        date: true,
        id: true,

        service: {
          select: {
            id: true,
          },
        },

        specialistId: true,
        status: true,
        time: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Bookings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Bookings",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async bookings(
    @common.Param() params: BookingsWhereUniqueInput
  ): Promise<Bookings | null> {
    const result = await this.service.bookings({
      where: params,
      select: {
        createdAt: true,
        date: true,
        id: true,

        service: {
          select: {
            id: true,
          },
        },

        specialistId: true,
        status: true,
        time: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Bookings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Bookings",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBookings(
    @common.Param() params: BookingsWhereUniqueInput,
    @common.Body() data: BookingsUpdateInput
  ): Promise<Bookings | null> {
    try {
      return await this.service.updateBookings({
        where: params,
        data: {
          ...data,

          service: data.service
            ? {
                connect: data.service,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          date: true,
          id: true,

          service: {
            select: {
              id: true,
            },
          },

          specialistId: true,
          status: true,
          time: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Bookings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Bookings",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBookings(
    @common.Param() params: BookingsWhereUniqueInput
  ): Promise<Bookings | null> {
    try {
      return await this.service.deleteBookings({
        where: params,
        select: {
          createdAt: true,
          date: true,
          id: true,

          service: {
            select: {
              id: true,
            },
          },

          specialistId: true,
          status: true,
          time: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
